### ISSUE TITLE
PlaceholderAPI format?

### ISSUE THREAD

**Issue by BlackBeltPanda** [kangarko/ChatControl-Free#350]
Trying to add placeholders from PlaceholderAPI and can't seem to figure it out. I'm used to using the Pro version but am setting up a server for a friend who's using the free version, lol.

Specifically, I'm trying to add a prefix to just nicknames like Essentials does. To do that, I crated a PlaceholderAPI javascript placeholder that compares the nickname to the username and, if it matches, returns the username. If the nickname is different, it returns the nickname prefixed with "~". PAPI is able to parse the placeholder so it's functioning properly.

Sadly, I can't seem to get the placeholder itself to work with ChatControl. The placeholder is "javascript_prefixed_nick". I've tried %javascript_prefixed_nick% and %javascript_prefixed_nick, neither of which worked. I also tested with %essentials_nickname% and %essentials_nickname, which also didn't work. Any ideas?

Thanks in advance. =)

**Comment by kangarko** [comment]
Hello, 

for PAPI placeholders always end your variables with %. Please note JavaScript variables are unsupported for ChatControl free. As a matter of course ensure you have the latest CCP free since there were upgrades to PAPI hook.

I need you to enable Debug in ChatControl's settings.yml, just set it to true and report console message at the time when the variable should be replaced. There should be 'Placeholders:' and 'Replacing' debug messages, post them here.

**Comment by BlackBeltPanda** [comment]
I tried the format of %placeholder_name%, no luck.
Using ChatControl v5.8.4.
"/papi parse me %placeholder%" returns the correct value.
This is all that prints to console/logs when trying to use the placeholder:
```
[ChatControl Debug] Placeholders: {essentials=com.extendedclip.papi.expansion.essentials.EssentialsExpansion@764b1418, javascript=com.extendedclip.papi.expansion.javascript.JavascriptExpansion@8fa29ec, player=com.extendedclip.papi.expansion.player.PlayerExpansion@1fbfc19a}
[Admin] %essentials_nickname%? test
```

**Comment by kangarko** [comment]
Seems I have some bad luck downloading (any) PAPI dependency, will try again on Monday/Tuesday :) 

![a](https://i.imgur.com/DYjIkUJ.png)

**Comment by kangarko** [comment]
Alright got it working, however it works fine on my system.  Here's what I've done:

1. Downloaded the Essentials ecloud extension
2. Made the edits as on the pic below:

![a](https://i.imgur.com/RFGutxc.png)

Any console errors? May I see the exact file as you are trying to use it?

**Comment by BlackBeltPanda** [comment]
Interestingly, when I format it exactly as you did it works fine. However, using this format it doesn't:
`%pl_prefix %essentials_nickname%: &f%message`

**Comment by kangarko** [comment]
Oh I see, ChatControl free is stupid as it's replacing parts of that variable because we did not use double percentage mark back then. This was solved in the pro version long time ago.

Anyways there's no proper fix for this than to change the variables completely, I can take a look into this when I have time.

**Comment by saletrak** [comment]
The solution is not using single-procent varables before double-procent values. Instead `%player` use `%player_name%` from Player extension to PlaceholderAPI (`/papi ecloud download Player`)

**Comment by kangarko** [comment]
I fixed it the hard way, renamed all variables to use the ChatControl Pro syntax. Please refer to the changelog of the next version.
