### ISSUE TITLE
Fonts & Smileys

### ISSUE THREAD

**Issue by Zazalanz** [kangarko/ChatControl-Free#374]
Hello, how can I disable chat fonts in chat? 

Also sending smileys in /msg isn't an option, how do I enable this.

Thanks for your time!

**Comment by Zazalanz** [comment]
bump

**Comment by kangarko** [comment]
There are no multiple fonts in MC as far as I know. You can block unicode letters by creating a rule that catches them. You can use google to look for 'how to catch unicode regex' phrase since regular expressions, regex, is an universal language.

You can just move chat.txt rules for smileys into rules.txt file to make them work everywhere.
