### ISSUE TITLE
1.14.4 Chatcontrol Console error

### ISSUE THREAD

**Issue by thames50** [kangarko/ChatControl-Free#394]
Hi I am receiving this console error which I think is causing lag on my server. Could you please help me determine what the problem is? 
[ChatControl (2).zip](https://github.com/kangarko/ChatControl-Free/files/4559918/ChatControl.2.zip)

https://pastebin.com/4QMySjwR

Thank you

**Comment by kangarko** [comment]
I apology for the delay, I believe this is caused by a syntax error in your regex filter. I went ahead to regex101.com where you can see where the problem is and fixed it for you:

`\b(m+(\W|\d|_))*o+(\W|\d|_)*t+(\W|\d|_)*h+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*e+(\W|\d|_)r+(\W|\d|_)*)`
