### ISSUE TITLE
Minecraft Version 1.19.1 and 1.19.2 (Paper 111 and 115): Issue Title: Error when using say from console with a player online

### ISSUE THREAD

**Issue by Momshroom** [kangarko/ChatControl-Free#74]
When using the say command from console, in Paper 111 (1.19.1)and 115(1.19.2), with protocolLib build 584 or 588 (tried both), I get the following error when a player is online and the say command is used from console (there isn't an error if no one is online): https://paste.gg/p/anonymous/c8f320fa17d5476ab6069f74808d09c9 
No errors were seen with say before updating to 1.19.1. (The protocolLib version was updated at the same time, which might be the issue, but the newer version of ProtocolLib is needed)

If you need more information, I'll be happy to supply it, but my configs don't seem relevant here, it seems to just be related to the new chat signing.

**Comment by kangarko** [comment]
Testing in 24 hours

**Comment by kangarko** [comment]
Unfortunately the amount of work to rewrite this for MC 1.19 is unfeasible for the Free version, you can consider upgrading to [ChatControl Red](https://mineacademy.org/chatcontrol) to get extended packet rules including 1.19 support. Sorry about this. Packet rules are capped on Free since 2015, nothing new.
